;             
CREATE USER IF NOT EXISTS SA SALT '8914bf814022dee8' HASH '57d185f7be09cb4f6053edbf54f65f46043002e8a04f439433e9d7f246574f14' ADMIN;           
CREATE CACHED TABLE PUBLIC.USER_DETAILS(
    ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);
ALTER TABLE PUBLIC.USER_DETAILS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);           
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER_DETAILS;            
INSERT INTO PUBLIC.USER_DETAILS(ID, FIRST_NAME, LAST_NAME) VALUES
(100, 'Mark', 'Ledwold');  
CREATE CACHED TABLE PUBLIC.APPLICATION_SCHEMA_UPGRADE(
    UPGRADE_ID INT NOT NULL,
    UPGRADE_DETAILS VARCHAR(255),
    UPGRADE_STATUS VARCHAR(255)
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APPLICATION_SCHEMA_UPGRADE;              
